cabal-version:      3.0
name:               plutus-context-builder
version:            3.0.0
synopsis:           A builder for ScriptContexts
description:
  Defines a builder for ScriptContexts, with helpers for commonly-needed uses.

homepage:           https://github.com/mlabs-haskell/plutus-test
bug-reports:
  https://github.com/Liqwid-Labs/mlabs-haskell/plutus-test/issues

license:

-- license-file:       LICENSE
author:             Koz Ross, Seungheon Oh
maintainer:
  Koz Ross <koz@mlabs.city>, Seungheon Oh <seungheon.ooh@gmail.com>

copyright:          (C) 2022 Liqwid Labs
category:           Plutus
build-type:         Simple
tested-with:        GHC ==9.2.5
extra-source-files: README.md

-- LICENSE
source-repository head
  type:     git
  location: https://github.com/mlabs-haskell/plutus-test

-- Common sections

common common-lang
  ghc-options:
    -Wall -Wcompat -Wincomplete-uni-patterns
    -Wincomplete-record-updates -Wredundant-constraints
    -Wmissing-export-lists -Wmissing-deriving-strategies -Werror

  build-depends:
    , base

  default-extensions:
    BangPatterns
    BinaryLiterals
    ConstraintKinds
    DataKinds
    DeriveAnyClass
    DeriveFunctor
    DeriveGeneric
    DeriveTraversable
    DerivingStrategies
    DerivingVia
    EmptyCase
    FlexibleContexts
    FlexibleInstances
    GeneralisedNewtypeDeriving
    HexFloatLiterals
    ImportQualifiedPost
    InstanceSigs
    KindSignatures
    LambdaCase
    MultiParamTypeClasses
    NumericUnderscores
    OverloadedLabels
    OverloadedStrings
    ScopedTypeVariables
    StandaloneDeriving
    TupleSections
    TypeApplications
    TypeFamilies
    TypeOperators
    NoFieldSelectors

  default-language:   Haskell2010

common common-tests
  import:        common-lang
  ghc-options:   -O2 -threaded -rtsopts -with-rtsopts=-N
  build-depends:
    , plutus-context-builder
    , plutus-ledger-api
    , plutus-tx
    , prettyprinter
    , tasty
    , tasty-hunit

-- Libraries

library
  import:          common-lang
  exposed-modules:
    Plutus.ContextBuilder.V2
    Plutus.ContextBuilder.V3
  other-modules:
    Plutus.ContextBuilder.V2.Base
    Plutus.ContextBuilder.V2.Certifying
    Plutus.ContextBuilder.V2.Check
    Plutus.ContextBuilder.V2.Internal
    Plutus.ContextBuilder.V2.Minting
    Plutus.ContextBuilder.V2.Rewarding
    Plutus.ContextBuilder.V2.Spending
    Plutus.ContextBuilder.V2.SubBuilder
    Plutus.ContextBuilder.V2.TxInfo
    Plutus.ContextBuilder.V3.Base
    Plutus.ContextBuilder.V3.Certifying
    Plutus.ContextBuilder.V3.Check
    Plutus.ContextBuilder.V3.Internal
    Plutus.ContextBuilder.V3.Minting
    Plutus.ContextBuilder.V3.Rewarding
    Plutus.ContextBuilder.V3.Spending
    Plutus.ContextBuilder.V3.SubBuilder
    Plutus.ContextBuilder.V3.TxInfo

  build-depends:
    , acc
    , bytestring
    , contravariant
    , cryptonite
    , memory
    , optics
    , plutus-ledger-api
    , plutus-tx
    , plutus-core >=1.40.0.0 && <1.41
    , prettyprinter
    , serialise

  hs-source-dirs:  src

-- Tests

test-suite sample
  import:         common-tests
  type:           exitcode-stdio-1.0
  main-is:        Main.hs
  other-modules:
    MintingBuilder
    SpendingBuilder

  build-depends:  optics
  hs-source-dirs: sample/
