{- | Module: Plutus.Context
 Copyright: (C) Liqwid Labs 2022
 License: Proprietary
 Maintainer: Koz Ross <koz@mlabs.city>
 Portability: GHC only
 Stability: Experimental

 Base builder and other specific builders.
-}
module Plutus.ContextBuilder (
  B.Builder (..),
  B.BaseBuilder,
  B.UTXO,
  B.output,
  B.address,
  B.input,
  B.referenceInput,
  B.continuing,
  B.continuingWith,
  B.credential,
  B.pubKey,
  B.script,
  B.withStakingCredential,
  B.withRefTxId,
  B.withHashDatum,
  B.withInlineDatum,
  B.withReferenceScript,
  B.withValue,
  B.withRefIndex,
  B.withRef,
  B.withRedeemer,
  B.signedWith,
  B.mint,
  B.mintWith,
  B.mintSingletonWith,
  B.extraData,
  B.extraRedeemer,
  B.txId,
  B.fee,
  B.unpack,
  B.withdrawal,
  B.timeRange,
  B.dcert,
  B.mkOutRefIndices,
  B.combinePair,
  B.combineMap,
  B.normalizeValue,
  B.normalizeUTXO,
  B.normalizeMint,
  B.sortMap,
  S.SpendingBuilder,
  S.withSpendingUTXO,
  S.withSpendingOutRef,
  S.withSpendingOutRefId,
  S.withSpendingOutRefIdx,
  S.buildSpending',
  S.buildSpending,
  S.tryBuildSpending,
  S.checkSpending,
  M.MintingBuilder,
  M.withMinting,
  M.buildMinting',
  M.buildMinting,
  M.tryBuildMinting,
  M.checkMinting,
  R.RewardingBuilder,
  R.withRewarding,
  R.buildRewarding',
  CE.CertifyingBuilder,
  CE.withCertifying,
  CE.buildCertifying',
  T.TxInfoBuilder (..),
  T.spends,
  T.mints,
  T.buildTxInfo,
  Sub.buildTxOut,
  Sub.buildTxInInfo,
  Sub.buildTxOuts,
  Sub.buildTxInInfos,
  Sub.buildDatumHashPairs,
  C.Checker (..),
  C.runChecker,
  C.CheckerError (..),
  C.CheckerPos (..),
  C.CheckerErrorType (..),
  C.basicError,
  C.checkAt,
  C.checkFoldable,
  C.checkIf,
  C.checkIfWith,
  C.checkBool,
  C.checkWith,
  C.checkBSLength,
  C.checkPositiveValue,
  C.checkTxId,
  C.handleErrors,
  C.checkSignatures,
  C.checkZeroSum,
  C.checkInputs,
  C.checkReferenceInputs,
  C.checkFail,
  C.checkMints,
  C.checkFee,
  C.checkOutputs,
  C.checkDatumPairs,
  C.checkPhase1,
  C.checkNormalized,
  C.renderErrors,
  C.flattenValue,
  C.checkValidatorRedeemer,
  C.checkValueNormalized,
  I.mkNormalized,
) where

import Plutus.ContextBuilder.Base qualified as B
import Plutus.ContextBuilder.Certifying qualified as CE
import Plutus.ContextBuilder.Check qualified as C
import Plutus.ContextBuilder.Minting qualified as M
import Plutus.ContextBuilder.Rewarding qualified as R
import Plutus.ContextBuilder.Spending qualified as S
import Plutus.ContextBuilder.SubBuilder qualified as Sub
import Plutus.ContextBuilder.TxInfo qualified as T

import Plutus.ContextBuilder.Internal qualified as I
